### ISSUE TITLE
cargo run fails with "Base address for bootloader did not match expected"

### ISSUE THREAD

**Issue by Luis-Hebendanz** [gamozolabs/chocolate_milk#23]
Hello,

I wanted to get the repo running but I encountered the error:
```bash
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/chocolate_milk`
warning: the feature `track_caller` has been stable since 1.46.0 and no longer requires an attribute to enable
 --> /home/lhebendanz/Projects/chocolate_milk/shared/lockcell/src/lib.rs:4:22
  |
4 | #![feature(const_fn, track_caller, llvm_asm)]
  |                      ^^^^^^^^^^^^
  |
  = note: `#[warn(stable_features)]` on by default

warning: 1 warning emitted

    Finished release [optimized + debuginfo] target(s) in 0.01s
Error: "Base address for bootloader did not match expected"
```

My active toolchain is:
```
nightly-x86_64-unknown-linux-gnu (default)
rustc 1.49.0-nightly (91a79fb29 2020-10-07)
```

**Comment by alureon** [comment]
I fixed this by changing the "base" linker flag in `./bootloader/cargo/config` to `0x7100`.

**Comment by Kharos102** [comment]
I had this issue but fixed it a different way, by fixing the warning showed in your post (removing "track_caller" as it's now a stable feature)

**Comment by gamozolabs** [comment]
Yeah, sadly here we don't have a great fix other than changing the base linker flag in the `.cargo/config`. Just the nature of kinda expecting the program to be located at a certain place after linking. Unfortunately, fudging this number is the "correct" fix here. Technically we could add a linker script, but that starts making it a lot less portable and convoluted to build. I prefer just using a normal linker.
