### ISSUE TITLE
Chocolate milk fails to build when using LLVM v7

### ISSUE THREAD

**Issue by m1el** [gamozolabs/chocolate_milk#5]
**What happened:**
I cloned the repository on commit 4e0c9313, ran `cargo run` from the project root, which resulted in the following error:
```
lld-link.exe: error: could not open /filealign:0x1000: no such file or directory
```

**Environment:**
- Windows 10 v1909
- `rustc 1.44.0-nightly`
- `LLVM v7.0.0`

**Expected outcomes:**
- `chocolate_milk` notifying the user that `lld-link` is too old
- removing requirement on `/filealign` command line flag
- adding documentation about minimal supported `lld-link` version

I've checked LLVM versions 9 and 10, and chocolate milk successfully built binaries for the bootloader and the kernel.

*Note:* `/filealign` command line flag was added in `llvm-svn: 361634`, https://reviews.llvm.org/D62124

**Comment by gamozolabs** [comment]
Thanks for the good writeup. I removed `/filealign`. I still use `/align` but that should be supported for pretty much any LLVM version I think.
